-- Near-exhaustive caliber reference list — rifle, handgun, and rimfire.
-- Safe to run multiple times: `calibers.name` has a UNIQUE constraint,
-- so ON CONFLICT DO NOTHING just skips anything already present (including
-- the 7 baseline calibers seeded by schema.sql).
--
-- Run this once in the Supabase SQL Editor.

INSERT INTO public.calibers (name, category) VALUES
  -- Rimfire
  ('.17 Mach 2', 'Rimfire'),
  ('.17 HMR', 'Rimfire'),
  ('.22 Short', 'Rimfire'),
  ('.22 Long Rifle', 'Rimfire'),
  ('.22 WMR (.22 Mag)', 'Rimfire'),
  ('.17 WSM', 'Rimfire'),
  ('.5mm Remington Magnum Rimfire', 'Rimfire'),

  -- Rifle — small/varmint centerfire
  ('.17 Hornet', 'Rifle'),
  ('.17 Remington', 'Rifle'),
  ('.17 Remington Fireball', 'Rifle'),
  ('.204 Ruger', 'Rifle'),
  ('.218 Bee', 'Rifle'),
  ('.220 Swift', 'Rifle'),
  ('.221 Remington Fireball', 'Rifle'),
  ('.222 Remington', 'Rifle'),
  ('.222 Remington Magnum', 'Rifle'),
  ('.223 Remington', 'Rifle'),
  ('.223 Wylde', 'Rifle'),
  ('5.56x45mm NATO', 'Rifle'),
  ('.22 Nosler', 'Rifle'),
  ('.224 Valkyrie', 'Rifle'),
  ('.22-250 Remington', 'Rifle'),
  ('.220 Weatherby Rocket', 'Rifle'),

  -- Rifle — 6mm / .243
  ('.243 Winchester', 'Rifle'),
  ('.243 Winchester Super Short Magnum (WSSM)', 'Rifle'),
  ('.243 Ackley Improved', 'Rifle'),
  ('6mm Creedmoor', 'Rifle'),
  ('6mm Remington', 'Rifle'),
  ('6mm ARC', 'Rifle'),
  ('6mm PPC', 'Rifle'),
  ('.240 Weatherby Magnum', 'Rifle'),
  ('.25 WSSM', 'Rifle'),
  ('.25-06 Remington', 'Rifle'),
  ('.25-20 Winchester', 'Rifle'),
  ('.257 Weatherby Magnum', 'Rifle'),
  ('.257 Roberts', 'Rifle'),

  -- Rifle — 6.5mm
  ('6.5 Grendel', 'Rifle'),
  ('6.5x47mm Lapua', 'Rifle'),
  ('6.5 Creedmoor', 'Rifle'),
  ('6.5x55mm Swedish', 'Rifle'),
  ('6.5 PRC', 'Rifle'),
  ('6.5-284 Norma', 'Rifle'),
  ('.264 Winchester Magnum', 'Rifle'),
  ('.260 Remington', 'Rifle'),
  ('6.5x284 Norma', 'Rifle'),
  ('6.5 Weatherby RPM', 'Rifle'),

  -- Rifle — .270 / 7mm
  ('.270 Winchester', 'Rifle'),
  ('.270 WSM', 'Rifle'),
  ('.270 Weatherby Magnum', 'Rifle'),
  ('6.8 Western', 'Rifle'),
  ('6.8 SPC', 'Rifle'),
  ('7mm-08 Remington', 'Rifle'),
  ('7mm Remington Magnum', 'Rifle'),
  ('7mm WSM', 'Rifle'),
  ('7mm PRC', 'Rifle'),
  ('7mm Weatherby Magnum', 'Rifle'),
  ('7mm Remington Ultra Magnum', 'Rifle'),
  ('.280 Remington', 'Rifle'),
  ('.280 Ackley Improved', 'Rifle'),
  ('.28 Nosler', 'Rifle'),
  ('7x57mm Mauser', 'Rifle'),
  ('7mm-300 Weatherby Magnum', 'Rifle'),

  -- Rifle — .30 caliber
  ('.30 Carbine', 'Rifle'),
  ('.30-30 Winchester', 'Rifle'),
  ('.30-06 Springfield', 'Rifle'),
  ('.300 Winchester Magnum', 'Rifle'),
  ('.300 WSM', 'Rifle'),
  ('.300 PRC', 'Rifle'),
  ('.300 Weatherby Magnum', 'Rifle'),
  ('.300 Remington Ultra Magnum', 'Rifle'),
  ('.300 H&H Magnum', 'Rifle'),
  ('.300 Blackout', 'Rifle'),
  ('.30-378 Weatherby Magnum', 'Rifle'),
  ('.300 Norma Magnum', 'Rifle'),
  ('.308 Winchester', 'Rifle'),
  ('7.62x39mm', 'Rifle'),
  ('7.62x54mmR', 'Rifle'),
  ('.303 British', 'Rifle'),
  ('.32 Winchester Special', 'Rifle'),

  -- Rifle — 8mm and up
  ('8mm Mauser (8x57mm JS)', 'Rifle'),
  ('.325 WSM', 'Rifle'),
  ('.338 Winchester Magnum', 'Rifle'),
  ('.338 Lapua Magnum', 'Rifle'),
  ('.338 Federal', 'Rifle'),
  ('.338 Remington Ultra Magnum', 'Rifle'),
  ('.338-06 A-Square', 'Rifle'),
  ('.340 Weatherby Magnum', 'Rifle'),
  ('9.3x62mm Mauser', 'Rifle'),
  ('.35 Remington', 'Rifle'),
  ('.35 Whelen', 'Rifle'),
  ('.350 Legend', 'Rifle'),
  ('.350 Remington Magnum', 'Rifle'),
  ('.356 Winchester', 'Rifle'),
  ('.358 Winchester', 'Rifle'),
  ('.375 H&H Magnum', 'Rifle'),
  ('.375 Ruger', 'Rifle'),
  ('.375 Winchester', 'Rifle'),
  ('.38-55 Winchester', 'Rifle'),
  ('.400 Legend', 'Rifle'),
  ('.404 Jeffery', 'Rifle'),
  ('.41 Action Express', 'Rifle'),
  ('.416 Remington Magnum', 'Rifle'),
  ('.416 Rigby', 'Rifle'),
  ('.44-40 Winchester', 'Rifle'),
  ('.444 Marlin', 'Rifle'),
  ('.45-70 Government', 'Rifle'),
  ('.450 Bushmaster', 'Rifle'),
  ('.450 Marlin', 'Rifle'),
  ('.458 SOCOM', 'Rifle'),
  ('.458 Winchester Magnum', 'Rifle'),
  ('.458 Lott', 'Rifle'),
  ('.470 Nitro Express', 'Rifle'),
  ('.500 Nitro Express', 'Rifle'),

  -- Handgun
  ('.22 LR (Handgun)', 'Handgun'),
  ('.25 ACP', 'Handgun'),
  ('.32 ACP', 'Handgun'),
  ('.32 H&R Magnum', 'Handgun'),
  ('.32-20 Winchester', 'Handgun'),
  ('.327 Federal Magnum', 'Handgun'),
  ('.380 ACP', 'Handgun'),
  ('9mm Luger (9x19mm)', 'Handgun'),
  ('9mm Makarov', 'Handgun'),
  ('.38 Special', 'Handgun'),
  ('.38 Super', 'Handgun'),
  ('.38-40 Winchester', 'Handgun'),
  ('.357 SIG', 'Handgun'),
  ('.357 Magnum', 'Handgun'),
  ('.357 Maximum', 'Handgun'),
  ('10mm Auto', 'Handgun'),
  ('.40 S&W', 'Handgun'),
  ('.41 Magnum', 'Handgun'),
  ('.44 Special', 'Handgun'),
  ('.44 Magnum', 'Handgun'),
  ('.44-40 Winchester (Handgun)', 'Handgun'),
  ('.45 ACP', 'Handgun'),
  ('.45 GAP', 'Handgun'),
  ('.45 Colt (Long Colt)', 'Handgun'),
  ('.454 Casull', 'Handgun'),
  ('.460 Rowland', 'Handgun'),
  ('.460 S&W Magnum', 'Handgun'),
  ('.475 Linebaugh', 'Handgun'),
  ('.480 Ruger', 'Handgun'),
  ('.50 Action Express', 'Handgun'),
  ('.500 S&W Magnum', 'Handgun'),
  ('.500 Wyoming Express', 'Handgun'),
  ('5.7x28mm', 'Handgun'),
  ('7.62x25mm Tokarev', 'Handgun'),
  ('.30 Super Carry', 'Handgun')
ON CONFLICT (name) DO NOTHING;
